# Generated by Django 4.0.3 on 2022-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(default='USER', max_length=64),
        ),
    ]
